### ISSUE TITLE
context class loader during object deserialization problem?

### ISSUE THREAD

**Issue by onsdk** [yyuu/jetty-nosql-memcached#12]
// use context class loader during object deserialization.
// thanks Daniel Peters!
sessionFactory.setClassLoader(getContext().getClassLoader());
log.info("use context class loader for session deserializer.");
// FIXME: is there any safe way to refer context's class loader?
// getContext().getClassLoader() may raise SecurityException.
// this will be determine by policy configuration of JRE.

About FIXME, I think you should try set Thread.currentThread().getContextClassLoader() again,otherwise, the kryo doesn't work without the security policy.

**Comment by yyuu** [comment]
Please send me back some PR if you still have this problem.
