### ISSUE TITLE
Remove/Invalidate session on TranscoderException

### ISSUE THREAD

**Issue by biguphpc** [yyuu/jetty-nosql-memcached#23]
Hi,

I was wondering if it would be possible to remove or invalidate the session when a TranscoderException occurs ? If you update your application in the cloud and the serializationIds haven been changed you'll get serializations errors and nothing works anymore. Instead It'd be great to remove the session from memcache so the application can create a new one with the updated objects.

Example : When using Vaadin 7.1.14 and upgrading to 7.2.0 the classes serialization Ids changed and now any running application with a memcached session stops working with a :
```
! Caused by: org.eclipse.jetty.nosql.kvs.session.TranscoderException: java.io.InvalidClassException: com.vaadin.server.VaadinSession; local class incompatible: stream classdesc serialVersionUID = 3298185606291138406, local class serialVersionUID = -1250609268898147328
! at org.eclipse.jetty.nosql.kvs.session.serializable.SerializableTranscoder.decode(SerializableTranscoder.java:49)
! at org.eclipse.jetty.nosql.kvs.session.serializable.SerializableSessionFactory.unpack(SerializableSessionFactory.java:36)
```

Instead it'd be great when the application is upgraded that they see their session has expired.

Thanks for this very useful project !

**Comment by yyuu** [comment]
Probably this has been solved by #29 and #30. Please send me back some PR if you still have problem.
