### ISSUE TITLE
XStreamSessionFactory - XStream 1.4.4 doesn't work properly with Java 8

### ISSUE THREAD

**Issue by marlonbernardes** [yyuu/jetty-nosql-memcached#24]
My application stopped working when I updated it's java version from 1.6 to 1.8. The reason behind it was that XStream wasn't deserializing Spring Security session attributes properly.

According to their own [website](http://xstream.codehaus.org/news.html), versions past 1.4.6 fix a lot of issues while using Java 8. 

The fix is to update XStream version from 1.4.4 to 1.4.7.

**Comment by yyuu** [comment]
Merged #25
